/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1ChartConfigSpecConfigMap
 */
export interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1ChartConfigSpecConfigMap {
    /**
     * Name is the name of the config map containing chart values to apply, e.g. node-exporter-chart-values.
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1ChartConfigSpecConfigMap
     */
    name: string;
    /**
     * Namespace is the namespace of the values config map, e.g. kube-system.
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1ChartConfigSpecConfigMap
     */
    namespace: string;
    /**
     * ResourceVersion is the Kubernetes resource version of the configmap. Used to detect if the configmap has changed, e.g. 12345.
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1ChartConfigSpecConfigMap
     */
    resourceVersion: string;
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1ChartConfigSpecConfigMapFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1ChartConfigSpecConfigMap {
    return ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1ChartConfigSpecConfigMapFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1ChartConfigSpecConfigMapFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1ChartConfigSpecConfigMap {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'namespace': json['namespace'],
        'resourceVersion': json['resourceVersion'],
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1ChartConfigSpecConfigMapToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1ChartConfigSpecConfigMap | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'namespace': value.namespace,
        'resourceVersion': value.resourceVersion,
    };
}


