/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterScaling
 */
export interface ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterScaling {
    /**
     * Max defines maximum number of worker nodes guest cluster is allowed to have.
     * @type {number}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterScaling
     */
    max: number;
    /**
     * Min defines minimum number of worker nodes required to be present in guest cluster.
     * @type {number}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterScaling
     */
    min: number;
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterScalingFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterScaling {
    return ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterScalingFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterScalingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterScaling {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'max': json['max'],
        'min': json['min'],
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterScalingToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterScaling | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'max': value.max,
        'min': value.min,
    };
}


