/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecConfigConfigMap
 */
export interface ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecConfigConfigMap {
    /**
     * Name is the name of the config map containing catalog values to apply, e.g. app-catalog-values.
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecConfigConfigMap
     */
    name: string;
    /**
     * Namespace is the namespace of the catalog values config map, e.g. giantswarm.
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecConfigConfigMap
     */
    namespace: string;
}

export function ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecConfigConfigMapFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecConfigConfigMap {
    return ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecConfigConfigMapFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecConfigConfigMapFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecConfigConfigMap {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'namespace': json['namespace'],
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecConfigConfigMapToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecConfigConfigMap | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'namespace': value.namespace,
    };
}


