/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfigConfigMap,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfigConfigMapFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfigConfigMapFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfigConfigMapToJSON,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfigSecret,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfigSecretFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfigSecretFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfigSecretToJSON,
} from './';

/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfig
 */
export interface ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfig {
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfigConfigMap}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfig
     */
    configMap: ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfigConfigMap;
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfigSecret}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfig
     */
    secret: ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfigSecret;
}

export function ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfigFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfig {
    return ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfigFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'configMap': ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfigConfigMapFromJSON(json['configMap']),
        'secret': ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfigSecretFromJSON(json['secret']),
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfigToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'configMap': ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfigConfigMapToJSON(value.configMap),
        'secret': ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecConfigSecretToJSON(value.secret),
    };
}


