/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestCluster,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestClusterFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestClusterFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestClusterToJSON,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestNode,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestNodeFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestNodeFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestNodeToJSON,
} from './';

/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuest
 */
export interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuest {
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestCluster}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuest
     */
    cluster: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestCluster;
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestNode}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuest
     */
    node: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestNode;
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuest {
    return ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cluster': ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestClusterFromJSON(json['cluster']),
        'node': ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestNodeFromJSON(json['node']),
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cluster': ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestClusterToJSON(value.cluster),
        'node': ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestNodeToJSON(value.node),
    };
}


