/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IoK8sApiCoreV1ObjectReference,
    IoK8sApiCoreV1ObjectReferenceFromJSON,
    IoK8sApiCoreV1ObjectReferenceFromJSONTyped,
    IoK8sApiCoreV1ObjectReferenceToJSON,
} from './';

/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneSpec
 */
export interface ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneSpec {
    /**
     * 
     * @type {IoK8sApiCoreV1ObjectReference}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneSpec
     */
    infrastructureRef: IoK8sApiCoreV1ObjectReference;
    /**
     * Number of master nodes.
     * @type {number}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneSpec
     */
    replicas?: number;
}

export function ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneSpecFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneSpec {
    return ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneSpecFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'infrastructureRef': IoK8sApiCoreV1ObjectReferenceFromJSON(json['infrastructureRef']),
        'replicas': !exists(json, 'replicas') ? undefined : json['replicas'],
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneSpecToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'infrastructureRef': IoK8sApiCoreV1ObjectReferenceToJSON(value.infrastructureRef),
        'replicas': value.replicas,
    };
}


