/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWS,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSToJSON,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1StatusCluster,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1StatusClusterFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1StatusClusterFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1StatusClusterToJSON,
} from './';

/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatus
 */
export interface ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatus {
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWS}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatus
     */
    aws: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWS;
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1StatusCluster}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatus
     */
    cluster: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1StatusCluster;
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatus {
    return ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'aws': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSFromJSON(json['aws']),
        'cluster': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1StatusClusterFromJSON(json['cluster']),
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'aws': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSToJSON(value.aws),
        'cluster': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1StatusClusterToJSON(value.cluster),
    };
}


