/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1ChartConfigSpecVersionBundle
 */
export interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1ChartConfigSpecVersionBundle {
    /**
     * 
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1ChartConfigSpecVersionBundle
     */
    version: string;
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1ChartConfigSpecVersionBundleFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1ChartConfigSpecVersionBundle {
    return ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1ChartConfigSpecVersionBundleFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1ChartConfigSpecVersionBundleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1ChartConfigSpecVersionBundle {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': json['version'],
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1ChartConfigSpecVersionBundleToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1ChartConfigSpecVersionBundle | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
    };
}


