/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpecCluster,
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpecClusterFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpecClusterFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpecClusterToJSON,
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpecProvider,
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpecProviderFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpecProviderFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpecProviderToJSON,
} from './';

/**
 * AWSClusterSpec is the spec part for the AWSCluster resource.
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpec
 */
export interface ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpec {
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpecCluster}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpec
     */
    cluster: ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpecCluster;
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpecProvider}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpec
     */
    provider: ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpecProvider;
}

export function ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpecFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpec {
    return ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpecFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cluster': ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpecClusterFromJSON(json['cluster']),
        'provider': ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpecProviderFromJSON(json['provider']),
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpecToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cluster': ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpecClusterToJSON(value.cluster),
        'provider': ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterSpecProviderToJSON(value.provider),
    };
}


