/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfigConfigMap,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfigConfigMapFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfigConfigMapFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfigConfigMapToJSON,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfigSecret,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfigSecretFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfigSecretFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfigSecretToJSON,
} from './';

/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfig
 */
export interface ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfig {
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfigConfigMap}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfig
     */
    configMap: ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfigConfigMap;
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfigSecret}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfig
     */
    secret: ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfigSecret;
}

export function ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfigFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfig {
    return ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfigFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'configMap': ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfigConfigMapFromJSON(json['configMap']),
        'secret': ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfigSecretFromJSON(json['secret']),
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfigToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'configMap': ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfigConfigMapToJSON(value.configMap),
        'secret': ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppSpecUserConfigSecretToJSON(value.secret),
    };
}


