/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecDNS,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecDNSFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecDNSFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecDNSToJSON,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecNTP,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecNTPFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecNTPFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecNTPToJSON,
} from './';

/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpec
 */
export interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpec {
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecDNS}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpec
     */
    dns: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecDNS;
    /**
     * 
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpec
     */
    _interface: string;
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecNTP}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpec
     */
    ntp: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecNTP;
    /**
     * 
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpec
     */
    privateNetwork: string;
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpec {
    return ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dns': ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecDNSFromJSON(json['dns']),
        '_interface': json['interface'],
        'ntp': ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecNTPFromJSON(json['ntp']),
        'privateNetwork': json['privateNetwork'],
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dns': ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecDNSToJSON(value.dns),
        'interface': value._interface,
        'ntp': ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecNTPToJSON(value.ntp),
        'privateNetwork': value.privateNetwork,
    };
}


