/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureVirtualNetwork
 */
export interface ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureVirtualNetwork {
    /**
     * CalicoSubnetCIDR is the CIDR for the calico subnet. It has to be also a worker subnet (Azure limitation).
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureVirtualNetwork
     */
    calicoSubnetCIDR: string;
    /**
     * CIDR is the CIDR for the Virtual Network.
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureVirtualNetwork
     */
    cidr: string;
    /**
     * is deleted. MasterSubnetCIDR is the CIDR for the master subnet.
     * 
     *     https://github.com/giantswarm/giantswarm/issues/4358
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureVirtualNetwork
     */
    masterSubnetCIDR: string;
    /**
     * WorkerSubnetCIDR is the CIDR for the worker subnet.
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureVirtualNetwork
     */
    workerSubnetCIDR: string;
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureVirtualNetworkFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureVirtualNetwork {
    return ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureVirtualNetworkFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureVirtualNetworkFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureVirtualNetwork {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'calicoSubnetCIDR': json['calicoSubnetCIDR'],
        'cidr': json['cidr'],
        'masterSubnetCIDR': json['masterSubnetCIDR'],
        'workerSubnetCIDR': json['workerSubnetCIDR'],
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureVirtualNetworkToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureVirtualNetwork | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'calicoSubnetCIDR': value.calicoSubnetCIDR,
        'cidr': value.cidr,
        'masterSubnetCIDR': value.masterSubnetCIDR,
        'workerSubnetCIDR': value.workerSubnetCIDR,
    };
}


