/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuest,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestToJSON,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecVersionBundle,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecVersionBundleFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecVersionBundleFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecVersionBundleToJSON,
} from './';

/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpec
 */
export interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpec {
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuest}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpec
     */
    guest: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuest;
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecVersionBundle}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpec
     */
    versionBundle: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecVersionBundle;
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpec {
    return ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'guest': ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestFromJSON(json['guest']),
        'versionBundle': ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecVersionBundleFromJSON(json['versionBundle']),
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'guest': ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestToJSON(value.guest),
        'versionBundle': ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecVersionBundleToJSON(value.versionBundle),
    };
}


