/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecHealthDocker,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecHealthDockerFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecHealthDockerFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecHealthDockerToJSON,
} from './';

/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecHealth
 */
export interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecHealth {
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecHealthDocker}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecHealth
     */
    docker: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecHealthDocker;
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecHealthFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecHealth {
    return ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecHealthFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecHealthFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecHealth {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'docker': ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecHealthDockerFromJSON(json['docker']),
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecHealthToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecHealth | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'docker': ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecHealthDockerToJSON(value.docker),
    };
}


