/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecNTP
 */
export interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecNTP {
    /**
     * 
     * @type {Array<string>}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecNTP
     */
    servers: Array<string>;
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecNTPFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecNTP {
    return ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecNTPFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecNTPFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecNTP {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'servers': json['servers'],
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecNTPToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeSpecNTP | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'servers': value.servers,
    };
}


