/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestMaster
 */
export interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestMaster {
    /**
     * 
     * @type {number}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestMaster
     */
    cpuCores?: number;
    /**
     * 
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestMaster
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestMaster
     */
    memorySizeGB?: number;
    /**
     * 
     * @type {number}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestMaster
     */
    storageSizeGB?: number;
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestMasterFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestMaster {
    return ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestMasterFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestMasterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestMaster {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cpuCores': !exists(json, 'cpuCores') ? undefined : json['cpuCores'],
        'id': json['id'],
        'memorySizeGB': !exists(json, 'memorySizeGB') ? undefined : json['memorySizeGB'],
        'storageSizeGB': !exists(json, 'storageSizeGB') ? undefined : json['storageSizeGB'],
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestMasterToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestMaster | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cpuCores': value.cpuCores,
        'id': value.id,
        'memorySizeGB': value.memorySizeGB,
        'storageSizeGB': value.storageSizeGB,
    };
}


