/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestWorker
 */
export interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestWorker {
    /**
     * 
     * @type {number}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestWorker
     */
    cpuCores?: number;
    /**
     * 
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestWorker
     */
    id: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestWorker
     */
    labels: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestWorker
     */
    memorySizeGB?: number;
    /**
     * 
     * @type {number}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestWorker
     */
    storageSizeGB?: number;
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestWorkerFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestWorker {
    return ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestWorkerFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestWorkerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestWorker {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cpuCores': !exists(json, 'cpuCores') ? undefined : json['cpuCores'],
        'id': json['id'],
        'labels': json['labels'],
        'memorySizeGB': !exists(json, 'memorySizeGB') ? undefined : json['memorySizeGB'],
        'storageSizeGB': !exists(json, 'storageSizeGB') ? undefined : json['storageSizeGB'],
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestWorkerToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1KVMClusterConfigSpecGuestWorker | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cpuCores': value.cpuCores,
        'id': value.id,
        'labels': value.labels,
        'memorySizeGB': value.memorySizeGB,
        'storageSizeGB': value.storageSizeGB,
    };
}


