/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatusProviderIngressLoadBalancer
 */
export interface ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatusProviderIngressLoadBalancer {
    /**
     * 
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatusProviderIngressLoadBalancer
     */
    publicIPName: string;
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatusProviderIngressLoadBalancerFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatusProviderIngressLoadBalancer {
    return ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatusProviderIngressLoadBalancerFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatusProviderIngressLoadBalancerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatusProviderIngressLoadBalancer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'publicIPName': json['publicIPName'],
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatusProviderIngressLoadBalancerToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatusProviderIngressLoadBalancer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'publicIPName': value.publicIPName,
    };
}


