/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterDockerDaemon,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterDockerDaemonFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterDockerDaemonFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterDockerDaemonToJSON,
} from './';

/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterDocker
 */
export interface ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterDocker {
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterDockerDaemon}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterDocker
     */
    daemon: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterDockerDaemon;
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterDockerFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterDocker {
    return ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterDockerFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterDockerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterDocker {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'daemon': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterDockerDaemonFromJSON(json['daemon']),
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterDockerToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterDocker | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'daemon': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterDockerDaemonToJSON(value.daemon),
    };
}


