/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * AWSConfigSpecAWSIngressELB deprecated since aws-operator v12 resources.
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigSpecAWSIngressELB
 */
export interface ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigSpecAWSIngressELB {
    /**
     * 
     * @type {number}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigSpecAWSIngressELB
     */
    idleTimeoutSeconds: number;
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigSpecAWSIngressELBFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigSpecAWSIngressELB {
    return ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigSpecAWSIngressELBFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigSpecAWSIngressELBFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigSpecAWSIngressELB {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'idleTimeoutSeconds': json['idleTimeoutSeconds'],
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigSpecAWSIngressELBToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigSpecAWSIngressELB | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'idleTimeoutSeconds': value.idleTimeoutSeconds,
    };
}


