/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisReleaseV1alpha1ReleaseSpecComponent
 */
export interface ComGithubGiantswarmApiextensionsPkgApisReleaseV1alpha1ReleaseSpecComponent {
    /**
     * Name of the component.
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisReleaseV1alpha1ReleaseSpecComponent
     */
    name: string;
    /**
     * Version of the component.
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisReleaseV1alpha1ReleaseSpecComponent
     */
    version: string;
}

export function ComGithubGiantswarmApiextensionsPkgApisReleaseV1alpha1ReleaseSpecComponentFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisReleaseV1alpha1ReleaseSpecComponent {
    return ComGithubGiantswarmApiextensionsPkgApisReleaseV1alpha1ReleaseSpecComponentFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisReleaseV1alpha1ReleaseSpecComponentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisReleaseV1alpha1ReleaseSpecComponent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'version': json['version'],
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisReleaseV1alpha1ReleaseSpecComponentToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisReleaseV1alpha1ReleaseSpecComponent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'version': value.version,
    };
}


