/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterKubernetesAPI
 */
export interface ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterKubernetesAPI {
    /**
     * 
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterKubernetesAPI
     */
    clusterIPRange: string;
    /**
     * 
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterKubernetesAPI
     */
    domain: string;
    /**
     * 
     * @type {number}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterKubernetesAPI
     */
    securePort: number;
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterKubernetesAPIFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterKubernetesAPI {
    return ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterKubernetesAPIFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterKubernetesAPIFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterKubernetesAPI {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'clusterIPRange': json['clusterIPRange'],
        'domain': json['domain'],
        'securePort': json['securePort'],
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterKubernetesAPIToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1ClusterKubernetesAPI | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'clusterIPRange': value.clusterIPRange,
        'domain': value.domain,
        'securePort': value.securePort,
    };
}


