/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1KVMConfigStatusKVM,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1KVMConfigStatusKVMFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1KVMConfigStatusKVMFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1KVMConfigStatusKVMToJSON,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1StatusCluster,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1StatusClusterFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1StatusClusterFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1StatusClusterToJSON,
} from './';

/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1KVMConfigStatus
 */
export interface ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1KVMConfigStatus {
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1StatusCluster}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1KVMConfigStatus
     */
    cluster: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1StatusCluster;
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1KVMConfigStatusKVM}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1KVMConfigStatus
     */
    kvm: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1KVMConfigStatusKVM;
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1KVMConfigStatusFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1KVMConfigStatus {
    return ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1KVMConfigStatusFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1KVMConfigStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1KVMConfigStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cluster': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1StatusClusterFromJSON(json['cluster']),
        'kvm': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1KVMConfigStatusKVMFromJSON(json['kvm']),
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1KVMConfigStatusToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1KVMConfigStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cluster': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1StatusClusterToJSON(value.cluster),
        'kvm': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1KVMConfigStatusKVMToJSON(value.kvm),
    };
}


