/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    IoK8sApimachineryPkgApisMetaV1APIGroupList,
    IoK8sApimachineryPkgApisMetaV1APIGroupListFromJSON,
    IoK8sApimachineryPkgApisMetaV1APIGroupListToJSON,
} from '../models';

/**
 * 
 */
export class ApisApi extends runtime.BaseAPI {

    /**
     * get available API versions
     */
    async getAPIVersionsRaw(): Promise<runtime.ApiResponse<IoK8sApimachineryPkgApisMetaV1APIGroupList>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/apis/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => IoK8sApimachineryPkgApisMetaV1APIGroupListFromJSON(jsonValue));
    }

    /**
     * get available API versions
     */
    async getAPIVersions(): Promise<IoK8sApimachineryPkgApisMetaV1APIGroupList> {
        const response = await this.getAPIVersionsRaw();
        return await response.value();
    }

}
