/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecConfig,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecConfigFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecConfigFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecConfigToJSON,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecStorage,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecStorageFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecStorageFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecStorageToJSON,
} from './';

/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpec
 */
export interface ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpec {
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecConfig}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpec
     */
    config: ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecConfig;
    /**
     * 
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpec
     */
    description: string;
    /**
     * LogoURL contains the links for logo image file for this app catalog
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpec
     */
    logoURL: string;
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecStorage}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpec
     */
    storage: ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecStorage;
    /**
     * Title is the name of the app catalog for this CR e.g. Catalog of Apps by Giant Swarm
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpec
     */
    title: string;
}

export function ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpec {
    return ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'config': ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecConfigFromJSON(json['config']),
        'description': json['description'],
        'logoURL': json['logoURL'],
        'storage': ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecStorageFromJSON(json['storage']),
        'title': json['title'],
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'config': ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecConfigToJSON(value.config),
        'description': value.description,
        'logoURL': value.logoURL,
        'storage': ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1AppCatalogSpecStorageToJSON(value.storage),
        'title': value.title,
    };
}


