/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnetPrivate,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnetPrivateFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnetPrivateFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnetPrivateToJSON,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnetPublic,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnetPublicFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnetPublicFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnetPublicToJSON,
} from './';

/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnet
 */
export interface ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnet {
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnetPrivate}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnet
     */
    _private: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnetPrivate;
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnetPublic}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnet
     */
    _public: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnetPublic;
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnetFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnet {
    return ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnetFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_private': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnetPrivateFromJSON(json['private']),
        '_public': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnetPublicFromJSON(json['public']),
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnetToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'private': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnetPrivateToJSON(value._private),
        'public': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AWSConfigStatusAWSAvailabilityZoneSubnetPublicToJSON(value._public),
    };
}


