/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusProviderNetwork,
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusProviderNetworkFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusProviderNetworkFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusProviderNetworkToJSON,
} from './';

/**
 * AWSClusterStatusProvider holds provider-specific status details.
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusProvider
 */
export interface ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusProvider {
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusProviderNetwork}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusProvider
     */
    network?: ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusProviderNetwork;
}

export function ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusProviderFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusProvider {
    return ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusProviderFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusProvider {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'network': !exists(json, 'network') ? undefined : ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusProviderNetworkFromJSON(json['network']),
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusProviderToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusProvider | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'network': ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusProviderNetworkToJSON(value.network),
    };
}


