/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1AWSClusterConfigSpecGuestWorker
 */
export interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1AWSClusterConfigSpecGuestWorker {
    /**
     * 
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1AWSClusterConfigSpecGuestWorker
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1AWSClusterConfigSpecGuestWorker
     */
    instanceType?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1AWSClusterConfigSpecGuestWorker
     */
    labels: { [key: string]: string; };
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1AWSClusterConfigSpecGuestWorkerFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1AWSClusterConfigSpecGuestWorker {
    return ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1AWSClusterConfigSpecGuestWorkerFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1AWSClusterConfigSpecGuestWorkerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1AWSClusterConfigSpecGuestWorker {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'instanceType': !exists(json, 'instanceType') ? undefined : json['instanceType'],
        'labels': json['labels'],
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1AWSClusterConfigSpecGuestWorkerToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1AWSClusterConfigSpecGuestWorker | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'instanceType': value.instanceType,
        'labels': value.labels,
    };
}


