/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1ChartSpec,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1ChartSpecFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1ChartSpecFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1ChartSpecToJSON,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1ChartStatus,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1ChartStatusFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1ChartStatusFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1ChartStatusToJSON,
    IoK8sApimachineryPkgApisMetaV1ObjectMeta,
    IoK8sApimachineryPkgApisMetaV1ObjectMetaFromJSON,
    IoK8sApimachineryPkgApisMetaV1ObjectMetaFromJSONTyped,
    IoK8sApimachineryPkgApisMetaV1ObjectMetaToJSON,
} from './';

/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1Chart
 */
export interface ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1Chart {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1Chart
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1Chart
     */
    kind?: string;
    /**
     * 
     * @type {IoK8sApimachineryPkgApisMetaV1ObjectMeta}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1Chart
     */
    metadata: IoK8sApimachineryPkgApisMetaV1ObjectMeta;
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1ChartSpec}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1Chart
     */
    spec: ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1ChartSpec;
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1ChartStatus}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1Chart
     */
    status: ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1ChartStatus;
}

export function ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1ChartFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1Chart {
    return ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1ChartFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1ChartFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1Chart {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apiVersion': !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'metadata': IoK8sApimachineryPkgApisMetaV1ObjectMetaFromJSON(json['metadata']),
        'spec': ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1ChartSpecFromJSON(json['spec']),
        'status': ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1ChartStatusFromJSON(json['status']),
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1ChartToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1Chart | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apiVersion': value.apiVersion,
        'kind': value.kind,
        'metadata': IoK8sApimachineryPkgApisMetaV1ObjectMetaToJSON(value.metadata),
        'spec': ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1ChartSpecToJSON(value.spec),
        'status': ComGithubGiantswarmApiextensionsPkgApisApplicationV1alpha1ChartStatusToJSON(value.status),
    };
}


