/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ComGithubGiantswarmApiextensionsPkgApisToolingV1alpha1AzureToolWorkspace,
    ComGithubGiantswarmApiextensionsPkgApisToolingV1alpha1AzureToolWorkspaceFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisToolingV1alpha1AzureToolWorkspaceFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisToolingV1alpha1AzureToolWorkspaceToJSON,
} from './';

/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisToolingV1alpha1AzureToolSpec
 */
export interface ComGithubGiantswarmApiextensionsPkgApisToolingV1alpha1AzureToolSpec {
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisToolingV1alpha1AzureToolWorkspace}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisToolingV1alpha1AzureToolSpec
     */
    workspace: ComGithubGiantswarmApiextensionsPkgApisToolingV1alpha1AzureToolWorkspace;
}

export function ComGithubGiantswarmApiextensionsPkgApisToolingV1alpha1AzureToolSpecFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisToolingV1alpha1AzureToolSpec {
    return ComGithubGiantswarmApiextensionsPkgApisToolingV1alpha1AzureToolSpecFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisToolingV1alpha1AzureToolSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisToolingV1alpha1AzureToolSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'workspace': ComGithubGiantswarmApiextensionsPkgApisToolingV1alpha1AzureToolWorkspaceFromJSON(json['workspace']),
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisToolingV1alpha1AzureToolSpecToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisToolingV1alpha1AzureToolSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'workspace': ComGithubGiantswarmApiextensionsPkgApisToolingV1alpha1AzureToolWorkspaceToJSON(value.workspace),
    };
}


