/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwnerGroup,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwnerGroupFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwnerGroupFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwnerGroupToJSON,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwnerUser,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwnerUserFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwnerUserFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwnerUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwner
 */
export interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwner {
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwnerGroup}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwner
     */
    group: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwnerGroup;
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwnerUser}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwner
     */
    user: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwnerUser;
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwnerFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwner {
    return ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwnerFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'group': ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwnerGroupFromJSON(json['group']),
        'user': ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwnerUserFromJSON(json['user']),
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwnerToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'group': ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwnerGroupToJSON(value.group),
        'user': ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1IgnitionSpecExtensionFileMetadataOwnerUserToJSON(value.user),
    };
}


