/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecFlannelSpec,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecFlannelSpecFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecFlannelSpecFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecFlannelSpecToJSON,
} from './';

/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecFlannel
 */
export interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecFlannel {
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecFlannelSpec}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecFlannel
     */
    spec: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecFlannelSpec;
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecFlannelFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecFlannel {
    return ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecFlannelFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecFlannelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecFlannel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'spec': ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecFlannelSpecFromJSON(json['spec']),
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecFlannelToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecFlannel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'spec': ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecFlannelSpecToJSON(value.spec),
    };
}


