/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestClusterAPI
 */
export interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestClusterAPI {
    /**
     * Endpoint is the guest cluster API endpoint.
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestClusterAPI
     */
    endpoint: string;
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestClusterAPIFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestClusterAPI {
    return ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestClusterAPIFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestClusterAPIFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestClusterAPI {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'endpoint': json['endpoint'],
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestClusterAPIToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestClusterAPI | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'endpoint': value.endpoint,
    };
}


