/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatusProvider,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatusProviderFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatusProviderFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatusProviderToJSON,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1StatusCluster,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1StatusClusterFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1StatusClusterFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1StatusClusterToJSON,
} from './';

/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatus
 */
export interface ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatus {
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1StatusCluster}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatus
     */
    cluster: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1StatusCluster;
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatusProvider}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatus
     */
    provider: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatusProvider;
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatusFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatus {
    return ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatusFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cluster': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1StatusClusterFromJSON(json['cluster']),
        'provider': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatusProviderFromJSON(json['provider']),
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatusToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cluster': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1StatusClusterToJSON(value.cluster),
        'provider': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigStatusProviderToJSON(value.provider),
    };
}


