/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneSpec,
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneSpecFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneSpecFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneSpecToJSON,
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneStatus,
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneStatusFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneStatusFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneStatusToJSON,
    IoK8sApimachineryPkgApisMetaV1ObjectMeta,
    IoK8sApimachineryPkgApisMetaV1ObjectMetaFromJSON,
    IoK8sApimachineryPkgApisMetaV1ObjectMetaFromJSONTyped,
    IoK8sApimachineryPkgApisMetaV1ObjectMetaToJSON,
} from './';

/**
 * The G8sControlPlane resource defines the Control Plane nodes (Kubernetes master nodes) of a Giant Swarm tenant cluster. It is reconciled by cluster-operator.
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlane
 */
export interface ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlane {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlane
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlane
     */
    kind?: string;
    /**
     * 
     * @type {IoK8sApimachineryPkgApisMetaV1ObjectMeta}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlane
     */
    metadata?: IoK8sApimachineryPkgApisMetaV1ObjectMeta;
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneSpec}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlane
     */
    spec: ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneSpec;
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneStatus}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlane
     */
    status: ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneStatus;
}

export function ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlane {
    return ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlane {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apiVersion': !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'metadata': !exists(json, 'metadata') ? undefined : IoK8sApimachineryPkgApisMetaV1ObjectMetaFromJSON(json['metadata']),
        'spec': ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneSpecFromJSON(json['spec']),
        'status': ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneStatusFromJSON(json['status']),
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlane | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apiVersion': value.apiVersion,
        'kind': value.kind,
        'metadata': IoK8sApimachineryPkgApisMetaV1ObjectMetaToJSON(value.metadata),
        'spec': ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneSpecToJSON(value.spec),
        'status': ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2G8sControlPlaneStatusToJSON(value.status),
    };
}


