/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusProvider,
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusProviderFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusProviderFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusProviderToJSON,
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2CommonClusterStatus,
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2CommonClusterStatusFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2CommonClusterStatusFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2CommonClusterStatusToJSON,
} from './';

/**
 * AWSClusterStatus holds status information about the cluster, populated once the cluster is in creation or created.
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatus
 */
export interface ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatus {
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2CommonClusterStatus}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatus
     */
    cluster?: ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2CommonClusterStatus;
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusProvider}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatus
     */
    provider?: ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusProvider;
}

export function ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatus {
    return ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cluster': !exists(json, 'cluster') ? undefined : ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2CommonClusterStatusFromJSON(json['cluster']),
        'provider': !exists(json, 'provider') ? undefined : ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusProviderFromJSON(json['provider']),
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cluster': ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2CommonClusterStatusToJSON(value.cluster),
        'provider': ComGithubGiantswarmApiextensionsPkgApisInfrastructureV1alpha2AWSClusterStatusProviderToJSON(value.provider),
    };
}


