/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZones,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesToJSON,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureNode,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureNodeFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureNodeFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureNodeToJSON,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureVirtualNetwork,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureVirtualNetworkFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureVirtualNetworkFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureVirtualNetworkToJSON,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1CredentialSecret,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1CredentialSecretFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1CredentialSecretFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1CredentialSecretToJSON,
} from './';

/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzure
 */
export interface ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzure {
    /**
     * 
     * @type {Array<number>}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzure
     */
    availabilityZones: Array<number>;
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1CredentialSecret}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzure
     */
    credentialSecret: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1CredentialSecret;
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZones}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzure
     */
    dnsZones: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZones;
    /**
     * 
     * @type {Array<ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureNode>}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzure
     */
    masters: Array<ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureNode>;
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureVirtualNetwork}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzure
     */
    virtualNetwork: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureVirtualNetwork;
    /**
     * 
     * @type {Array<ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureNode>}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzure
     */
    workers: Array<ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureNode>;
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzure {
    return ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzure {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'availabilityZones': json['availabilityZones'],
        'credentialSecret': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1CredentialSecretFromJSON(json['credentialSecret']),
        'dnsZones': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesFromJSON(json['dnsZones']),
        'masters': ((json['masters'] as Array<any>).map(ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureNodeFromJSON)),
        'virtualNetwork': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureVirtualNetworkFromJSON(json['virtualNetwork']),
        'workers': ((json['workers'] as Array<any>).map(ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureNodeFromJSON)),
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzure | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'availabilityZones': value.availabilityZones,
        'credentialSecret': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1CredentialSecretToJSON(value.credentialSecret),
        'dnsZones': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesToJSON(value.dnsZones),
        'masters': ((value.masters as Array<any>).map(ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureNodeToJSON)),
        'virtualNetwork': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureVirtualNetworkToJSON(value.virtualNetwork),
        'workers': ((value.workers as Array<any>).map(ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureNodeToJSON)),
    };
}


