/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * AzureConfigSpecAzureDNSZonesDNSZone points to a DNS Zone in Azure.
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZone
 */
export interface ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZone {
    /**
     * Name is the name of the zone.
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZone
     */
    name: string;
    /**
     * ResourceGroup is the resource group of the zone.
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZone
     */
    resourceGroup: string;
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZoneFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZone {
    return ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZoneFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZone {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'resourceGroup': json['resourceGroup'],
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZoneToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZone | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'resourceGroup': value.resourceGroup,
    };
}


