/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuest,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestToJSON,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecVersionBundle,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecVersionBundleFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecVersionBundleFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecVersionBundleToJSON,
} from './';

/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpec
 */
export interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpec {
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuest}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpec
     */
    guest: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuest;
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecVersionBundle}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpec
     */
    versionBundle: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecVersionBundle;
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpec {
    return ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'guest': ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestFromJSON(json['guest']),
        'versionBundle': ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecVersionBundleFromJSON(json['versionBundle']),
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'guest': ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecGuestToJSON(value.guest),
        'versionBundle': ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1DrainerConfigSpecVersionBundleToJSON(value.versionBundle),
    };
}


