/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZone,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZoneFromJSON,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZoneFromJSONTyped,
    ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZoneToJSON,
} from './';

/**
 * AzureConfigSpecAzureDNSZones contains the DNS Zones of the cluster.
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZones
 */
export interface ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZones {
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZone}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZones
     */
    api: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZone;
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZone}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZones
     */
    etcd: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZone;
    /**
     * 
     * @type {ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZone}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZones
     */
    ingress: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZone;
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZones {
    return ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZones {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'api': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZoneFromJSON(json['api']),
        'etcd': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZoneFromJSON(json['etcd']),
        'ingress': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZoneFromJSON(json['ingress']),
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZones | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'api': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZoneToJSON(value.api),
        'etcd': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZoneToJSON(value.etcd),
        'ingress': ComGithubGiantswarmApiextensionsPkgApisProviderV1alpha1AzureConfigSpecAzureDNSZonesDNSZoneToJSON(value.ingress),
    };
}


