/* tslint:disable */
/* eslint-disable */
/**
 * giantswarm-cp-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeDocker
 */
export interface ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeDocker {
    /**
     * 
     * @type {string}
     * @memberof ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeDocker
     */
    image: string;
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeDockerFromJSON(json: any): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeDocker {
    return ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeDockerFromJSONTyped(json, false);
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeDockerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeDocker {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'image': json['image'],
    };
}

export function ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeDockerToJSON(value?: ComGithubGiantswarmApiextensionsPkgApisCoreV1alpha1FlannelConfigSpecBridgeDocker | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'image': value.image,
    };
}


